# Site settings
title: A place to say
email: guoxiao08@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is just another place to say something, mostly about technology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://guoxiao.github.io" # the base hostname & protocol for your site
twitter_username: guoxiao
github_username:  guoxiao

# Build settings
markdown: redcarpet
